apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pod-monitor1
  namespace: default
  annotations:
    arms.prometheus.io/discovery: 'true'
spec:
  selector:
    matchLabels:
      inference-framework: vllm
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - interval: 30s
      targetPort: 8000
      path: /metrics
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: pod_name
        - action: replace
          sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: pod_namespace
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_metrics_inference_stack_model_group
          targetLabel: model_group
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_rolebasedgroup_workloads_x_k8s_io_role
          targetLabel: serving_role