apiVersion: workloads.x-k8s.io/v1alpha1
kind: RoleBasedGroup
metadata:
  name: lws-runtime
spec:
  roles:
    - name: scheduler
      replicas: 1
      template:
        spec:
          containers:
            - name: scheduler
              image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
              ports:
                - containerPort: 80
      engineRuntimes:
        - profileName: patio-runtime

    - name: worker
      replicas: 1
      workload:
        apiVersion: leaderworkerset.x-k8s.io/v1
        kind: LeaderWorkerSet
      leaderWorkerSet:
        size: 2
        patchLeaderTemplate:
            metadata:
              labels:
                role: leader
        patchWorkerTemplate:
            metadata:
              labels:
                role: worker
      template:
        spec:
          containers:
            - name: vllm
              image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
              ports:
                - name: http
                  containerPort: 8000
      engineRuntimes:
        - profileName: patio-runtime
          containers:
            - name: patio-runtime
              args:
                - --instance-info={"topo_type":"Mooncake","worker_role":"decode_only","ep_size":"16","gpu_per_node":"8"}
              env:
                - name: TOPO_COLLECTOR_ENDPOINT
                  value: http://lws-runtime-scheduler-0.lws-runtime-scheduler:9091
---
apiVersion: workloads.x-k8s.io/v1alpha1
kind: ClusterEngineRuntimeProfile
metadata:
  name: patio-runtime
spec:
  volumes:
    - emptyDir: {}
      name: patio-group-config
  containers:
    - name: patio-runtime
      image: registry-cn-hangzhou.ack.aliyuncs.com/dev/patio-runtime:v0.2.0
      volumeMounts:
        - name: patio-group-config
          mountPath: /etc/patio
