---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - workloads.x-k8s.io
  resources:
  - rolebasedgroupsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.x-k8s.io
  resources:
  - rolebasedgroupsets/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.x-k8s.io
  resources:
  - rolebasedgroupsets/status
  verbs:
  - get
  - patch
  - update
