apiVersion: v1
data:
  scheduler-run.sh: |-
    #!/bin/bash

    CONFIG_FILE="/etc/patio/instance-config.yaml"
    args=("$@")

    # 监控文件是否存在，并执行相应操作
    while true; do
      if [[ -f "$CONFIG_FILE" ]]; then
        # 执行scheduler 命令
        decode_count=$(grep -c 'work_role: decode-only' $CONFIG_FILE)
        prefill_count=$(grep -c 'work_role: prefill-only' $CONFIG_FILE)
        echo \"decode=$decode_count prefill=$prefill_count\"
    
        /app/scheduler/scheduler ${args[@]} -decode-ratio=$decode_count -prefill-ratio=$prefill_count | tee -a /app/scheduler.log &

        scheduler_pid=$!

        # 获取文件的初始修改时间
        last_mod_time=$(stat -c %Y "$CONFIG_FILE")

        # 后台进程监控文件变更
        while true; do
          sleep 30

          # 获取当前文件的修改时间
          current_mod_time=$(stat -c %Y "$CONFIG_FILE")

          # 检查修改时间是否发生变化
          if [[ $current_mod_time -ne $last_mod_time ]]; then
            echo "File has changed cur_mod_time [$current_mod_time] not equal last_mod_time [$last_mod_time], exiting script."
            kill $scheduler_pid
            echo "scheduler process killed successfully"
            break
          fi
        done
      else
        echo "Config file not found. Waiting 5 seconds before rechecking."
        sleep 5
      fi
    done
kind: ConfigMap
metadata:
  name: scheduler-run
  namespace: default