apiVersion: workloads.x-k8s.io/v1alpha1
kind: RoleBasedGroup
metadata:
  name: sglang-multi-nodes
spec:
  roles:
    - name: worker
      replicas: 2
      template:
        spec:
          volumes:
            - name: model
              persistentVolumeClaim:
                claimName: llm-model
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 1Gi
          containers:
            - name: sglang-leader
              image: <sglang-image>
              command:
                - sh
                - -c
                - "python3 -m sglang.launch_server --model-path=/models/Qwen2.5-Coder-1.5B-Instruct --tp=2 \
                  --dist-init-addr=$(GROUP_NAME)-$(ROLE_NAME)-0.$(GROUP_NAME)-$(ROLE_NAME):5000 \ 
                  --nnodes=$(ROLES_WORKER_SIZE) --node-rank=$(ROLE_INDEX) --trust-remote-code --host 0.0.0.0 --port 8000"
              ports:
                - containerPort: 8000
              resources:
                limits:
                  nvidia.com/gpu: "1"
              volumeMounts:
                - mountPath: /models/Qwen2.5-Coder-1.5B-Instruct
                  name: model
                - mountPath: /dev/shm
                  name: dshm


