apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbgs-controller-role
rules:
  - apiGroups:
      - workloads.x-k8s.io
    resources:
      - rolebasedgroupsets
      - rolebasedgroups
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "get"
    resourceNames:
      - "rolebasedgroupsets.workloads.x-k8s.io"
      - "rolebasedgroups.workloads.x-k8s.io"
  - apiGroups:
      - workloads.x-k8s.io
    resources:
      - rolebasedgroupsets/status
      - rolebasedgroups/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - controllerrevisions/finalizers
      - statefulsets/finalizers
    verbs:
      - update
  - apiGroups:
      - apps
    resources:
      - controllerrevisions/status
      - statefulsets/status
    verbs:
      - get
      - patch
      - update