apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-benchmark
  labels:
    app: vllm-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-benchmark
  template:
    metadata:
      labels:
        app: vllm-benchmark
        alibabacloud.com/fluid-sidecar-target: acs
        alibabacloud.com/acs: "true"
        alibabacloud.com/compute-qos: default
        alibabacloud.com/compute-class: general-purpose
    spec:
      volumes:
        - name: llm-model
          persistentVolumeClaim:
            claimName: llm-model
      containers:
        - name: vllm-benchmark
          image: kube-ai-registry.cn-shanghai.cr.aliyuncs.com/kube-ai/vllm-benchmark:v1.1.0
          command:
            - "sh"
            - "-c"
            - "sleep inf"
          resources:
            limits:
              cpu: "8"
              memory: 40Gi
            requests:
              cpu: "8"
              memory: 40Gi
          volumeMounts:
            - mountPath: /models/QwQ-32B/
              name: llm-model