# Default values for rbgs-controller.

replicaCount: 2

image:
  repository: registry-cn-hangzhou.ack.aliyuncs.com/acs/rbgs-controller
  pullPolicy: IfNotPresent
  tag: v0.3.0

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

resources:
  limits:
    cpu: 1000m
    memory: 1536Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

